#!/bin/bash

# Copyright (c) 2022 fkmatsuda <fabio@fkmatsuda.dev>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set_touchpad() {

	gsettings set org.gnome.desktop.peripherals.touchpad send-events $1
	echo "$1"

}

get_touchpad() {
	case "$(gsettings get org.gnome.desktop.peripherals.touchpad send-events | cut -d "'" -f 2)" in
		'enabled')
			return 1
			;;
		'disabled')
			return 0
			;;
		*)
			return 255
			;;
		esac
}

case "$1" in
	'on')
		set_touchpad enabled
		;;
	'off')
		set_touchpad disabled
		;;
	'status')
		get_touchpad
		status=$?
		if [ $status -eq 1 ]; then
			echo "enabled"
			exit 0
		elif [ $status -eq 0 ]; then
			echo "disabled"
			exit 0
		else
			echo "invalid state"
			exit 255
		fi
		;;
	'toggle')
		get_touchpad
		status=$?
		if [ $status -eq 1 ]; then
			set_touchpad disabled
			exit 0
		elif [ $status -eq 0 ]; then
			set_touchpad enabled
			exit 0
		else
			echo "invalid state"
			exit 255
		fi
		;;
	*)
	echo 
	echo "Usage: $0 { on | off | toggle | status }"
	echo
	exit 1
	;;
esac

exit 0
